spring.application.name=demo_G1

spring.datasource.url=jdbc:mysql://localhost:3306/demo_db
spring.datasource.username=root
spring.datasource.password=#Big.Mama_Chungus$

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

server.port=8080
